apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: weave-gateway
  namespace: weave-dashboard
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
