---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: infrastrcuture-demo
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
---