apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-version
  namespace: flux-system
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
  labels:
    toolkit.fluxcd.io/tenant: sre-team
data:
  version: 1.16.1