# pathch by removing mountPropagation: Bidirectional
# kustomize build gitops/infrastructure/secrets-store-csi-driver --enable-helm | sed '/mountPropagation: Bidirectional/d'
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmChartInflationGenerator:
- chartName: secrets-store-csi-driver
  chartRepoUrl: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
  chartVersion: 1.3.0
  releaseName: csi-secrets-store
  releaseNamespace: kube-system
  # valuesFile: values.yaml

patchesStrategicMerge: 
- patch.yaml
