apiVersion: v1
kind: Namespace
metadata:
  name: infrastrcuture-demo
  labels:
    kubernetes.io/metadata.name: infrastrcuture-demo
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: infrastrcuture-demo
  labels:
    app: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: httpd
        name: httpd
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpd
  name: httpd
  namespace: infrastrcuture-demo
spec:
  selector:
    app: httpd
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpd-localhost
  namespace: infrastrcuture-demo
spec:
  ingressClassName: nginx
  rules:
  - host: httpd.dev.local.gd
    http:
      paths:
      - backend:
          service:
            name: httpd
            port:
              number: 80
        path: /
        pathType: Prefix
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpd
  namespace: infrastrcuture-demo
spec:
  hosts:
    - "httpd.dev.local.gd"
  http:
    - route:
        - destination:
            host: httpd
            port:
              number: 80
  gateways:
    - "istio-system/public-gateway"
---
