---
- name: "podinfo"
  namespace: "ingress-nginx"
  service: "ingress-nginx-controller"
  url: "http://podinfo.local.gd"


- name: "weave-gitops-dashboard"
  namespace: "dashboard"
  service: "weave-gitops"
  url: "http://gitops.local.gd"
---





