name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup tools
        uses: ./.github/actions/tools
      - name: Check Paths
        run: ls -asl $GITHUB_PATH
      - name: Validate manifests
        run: ./local-dev/iaac/test/validate.sh